version: "3.9"

services:
  postgres:
    container_name: postgres_currency_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      GDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5410:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: